version: "2"

services:
  recorder:
    build: .
    command: --username $TARGET_USER
    restart: unless-stopped
    environment:
      OUTPUT_PATH: $OUTPUT_PATH
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
    user: "1000:1000"
